### ISSUE TITLE
Confusing traceback at exit

### ISSUE THREAD

**Issue by jojo989** [nekitdev/gd.py#134]
soo, everytime when i execute a script i get this error:
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022C60627790>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

im not sure if my code has an error or smth

**Comment by johnslavik** [comment]
No, it's not your code that has an error. This "error" has no consequences other than the confusing message in stderr upon closing the network IO communication. A fix will come in v2.

Thanks for reporting this.
