### ISSUE TITLE
FileNotFoundError: /opt/homebrew/lib/python3.11/site-packages/gd/submodules/schema/gd/schema/artist.capnp

### ISSUE THREAD

**Issue by Obsivium** [nekitdev/gd.py#168]
# when i run even a simple code it gives this error

> FileNotFoundError: /opt/homebrew/lib/python3.11/site-packages/gd/submodules/schema/gd/schema/artist.capnp

Code : 
``` python
import gd

client = gd.Client()
```
entire error
```
Traceback (most recent call last):
  File "/Users/-----/main.py", line 1, in <module>
    import gd
  File "/opt/homebrew/lib/python3.11/site-packages/gd/__init__.py", line 11, in <module>
    from gd import (
  File "/opt/homebrew/lib/python3.11/site-packages/gd/api/__init__.py", line 1, in <module>
    from gd.api.artist import ArtistAPI
  File "/opt/homebrew/lib/python3.11/site-packages/gd/api/artist.py", line 11, in <module>
    from gd.schema import ArtistAPISchema
  File "/opt/homebrew/lib/python3.11/site-packages/gd/schema.py", line 39, in <module>
    artist = load_module("artist")
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gd/schema.py", line 32, in load_module
    raise FileNotFoundError(path_string)
FileNotFoundError: /opt/homebrew/lib/python3.11/site-packages/gd/submodules/schema/gd/schema/artist.capn
```

**Comment by allernotfound** [comment]
I'm having a very similar problem, but on Windows 11.
Here's my error:

```
Traceback (most recent call last):
  File "C:\Users\*\Documents\Scripts\Python\Apps\gdinfobot\main.py", line 1, in <module>
    import gd
  File "C:\Users\*\Documents\Scripts\Python\Apps\gdinfobot\venv\Lib\site-packages\gd\__init__.py", line 11, in <module>
    from gd import (
  File "C:\Users\*\Documents\Scripts\Python\Apps\gdinfobot\venv\Lib\site-packages\gd\api\__init__.py", line 1, in <module>
    from gd.api.artist import ArtistAPI
  File "C:\Users\*\Documents\Scripts\Python\Apps\gdinfobot\venv\Lib\site-packages\gd\api\artist.py", line 11, in <module>
    from gd.schema import ArtistAPISchema
  File "C:\Users\*\Documents\Scripts\Python\Apps\gdinfobot\venv\Lib\site-packages\gd\schema.py", line 39, in <module>
    artist = load_module("artist")
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\Documents\Scripts\Python\Apps\gdinfobot\venv\Lib\site-packages\gd\schema.py", line 32, in load_module
    raise FileNotFoundError(path_string)
FileNotFoundError: C:/Users/*/Documents/Scripts/Python/Apps/gdinfobot/venv/Lib/site-packages/gd/submodules/schema/gd/schema/artist.capnp

Process finished with exit code 1
```
