### ISSUE TITLE
HTTP Error.

### ISSUE THREAD

**Issue by ghost** [nekitdev/gd.py#26]
### Summary
I was trying to make a bot and i wanted to add a feature to it which gives information about Geometry Dash, unfortunately this pops whenever i try to run in, but the same code works on another device, no changes at all.

### Results
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print(botGD.level(23262780))
  File "/home/runner/PelasePlsae/botGD.py", line 44, in level
    return client.run(get_level_info(ID))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/gd/client.py", line 2322, in run
    return utils.run(coro, loop=self.loop, debug=debug)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/gd/utils/_async.py", line 197, in run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/PelasePlsae/botGD.py", line 6, in get_level_info
    await client.login('******', '******')
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/gd/client.py", line 724, in login
    account_id, player_id = await self.session.login(user=user, password=password)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/gd/session.py", line 492, in login
    resp = await self.http.request(Route.LOGIN, payload, error_codes=codes)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/gd/utils/http_request.py", line 266, in request
    resp = await self.fetch(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/gd/utils/http_request.py", line 189, in fetch
    raise HTTPError(exc) from None
gd.errors.HTTPError: Failed to process HTTP request. Caused by: <ClientConnectorError> (Cannot connect to host www.boomlings.com:80 ssl:default [Connect call failed ('162.216.16.96', 80)])

**Comment by spookybear0** [comment]
This could mean that your internet is not stable enough, does it work on gd?

**Comment by ghost** [comment]
Maybe i think im not allowed to access the database using the other internet on another device, im just hoping for a fix but thanks!

**Comment by spookybear0** [comment]
Try logging in without a username and password as params instead of ("", "")

**Comment by ghost** [comment]
> Try logging in without a username and password as params instead of ("", "")

no, i just edited it to hide my username and password, i used an account to login

**Comment by spookybear0** [comment]
weird

**Comment by nekitdev** [comment]
Closing this issue as it is inactive.
