### ISSUE TITLE
Can not use due to AttributeError occurring?

### ISSUE THREAD

**Issue by Bigmancozmo** [nekitdev/gd.py#35]
When I run the program I get the error:
```python
AttributeError: module "gd" has no attribute "Client".
```

**Comment by spookybear0** [comment]
Are you using the latest version? (and what is the name of your python file)

**Comment by Bigmancozmo** [comment]
File's name is `code.py` and I am using the latest version.

**Comment by nekitdev** [comment]
You can check the version via
```sh
py -3 -m gd --version
```

**Comment by PolyTree18** [comment]
```

Traceback (most recent call last):
  File "E:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\Python39\lib\site-packages\gd\__main__.py", line 45, in <module>
    gd_group()
  File "E:\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "E:\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "E:\Python\Python39\lib\site-packages\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "E:\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "E:\Python\Python39\lib\site-packages\gd\__main__.py", line 16, in gd_group
    click.echo("\n".join(collect_versions()))
  File "E:\Python\Python39\lib\site-packages\gd\__main__.py", line 37, in collect_versions
    yield f"- gd.py {version_from_info(gd.version_info)}"
AttributeError: module 'gd' has no attribute 'version_info'
```

**Comment by megahomyak** [comment]
> When I run the program I get the error:
> 
> ```python
> AttributeError: module "gd" has no attribute "Client".
> ```

Have you installed `gd.py`? Maybe the library you installed is named `gd`?
(Wrong: `pip install gd`
Correct: `pip install gd.py`)

**Comment by nekitdev** [comment]
Closed this due to inactivity.

**Comment by PolyTree18** [comment]
> > When I run the program I get the error:
> > ```python
> > AttributeError: module "gd" has no attribute "Client".
> > ```
> 
> Did you installed `gd.py`? Maybe the library you installed is named `gd`?
> (Wrong: `pip install gd`
> Correct: `pip install gd.py`)

Yes, i installed gd.py
