### ISSUE TITLE
403 when calling getGJUsers20.php

### ISSUE THREAD

**Issue by megahomyak** [nekitdev/gd.py#40]
### Summary

`await self.gd_client.find_user(player_name)` => `gd.errors.HTTPError: Failed to process HTTP request. Caused by: Error<ClientResponseError>(403, message='Forbidden', url=URL('http://www.boomlings.com/database/getGJUsers20.php'))`

### Traceback

```
Traceback (most recent call last):
  File "main_logic.py", line 333, in reply_to_vk_message
    await self.vk_worker.reply(await self.handle_command(
  File "main_logic.py", line 301, in handle_command
    handling_result: HandlingResult = await command_.handler(
  File "/home/ubuntu/GDL/handlers/handlers.py", line 163, in get_player_info
    await self.gd_worker.get_player(player_name)
  File "/home/ubuntu/GDL/requests_workers/gd_worker.py", line 17, in get_player
    player = await self.gd_client.find_user(player_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gd/client.py", line 558, in find_user
    data = await self.session.search_user(query, return_abstract=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gd/session.py", line 221, in search_user
    resp = await self.http.request(Route.USER_SEARCH, payload, error_codes=codes)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gd/utils/http_request.py", line 280, in request
    resp = await self.fetch(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gd/utils/http_request.py", line 201, in fetch
    raise HTTPError(exc) from None
gd.errors.HTTPError: Failed to process HTTP request. Caused by: Error<ClientResponseError>(403, message='Forbidden', url=URL('http://www.boomlings.com/database/getGJUsers20.php'))
```

### My code

https://github.com/megahomyak/GDL/blob/c19b8d4ca770cf2885fb38e4eca834ab2b42bf14/requests_workers/gd_worker.py#L17

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- python v3.8.5-final
- gd.py v0.11.0-final
- aiohttp v3.7.2
- click v7.1.2
- system Windows 10 10.0.19041

**Comment by nekitdev** [comment]
It is recommended to update to the latest version, and use `Client.search_user` instead. Said function loads full information on the user, so you'd only need that in your code.

**Comment by megahomyak** [comment]
It's very strange, it works normally on my laptop, but gives me 403 on my server!

**Comment by megahomyak** [comment]
Strange, but it works normally on my laptop (both `.find_user()` and `.search_user()`), but neither of those are working on my server!
