### ISSUE TITLE
Level comment not work on Python 3.10

### ISSUE THREAD

**Issue by thelittlepony** [nekitdev/gd.py#41]
I trying to comment level but i'm getting that:

`Traceback (most recent call last):
  File "G:\Мой диск\GDClient\main.py", line 70, in <module>
    client.run(clientC())
  File "C:\Users\Denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gd\client.py", line 2350, in run
    return utils.run(coro, loop=self.loop, debug=debug)
  File "C:\Users\Denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gd\utils\async_utils.py", line 193, in run
    return loop.run_until_complete(coro)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "G:\Мой диск\GDClient\main.py", line 64, in clientC
    level = await client.get_level(levelToCommentID)
  File "C:\Users\Denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gd\client.py", line 625, in get_level
    level_data, creator_data, song_data = await self.session.get_level_info(level_id)
  File "C:\Users\Denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gd\session.py", line 242, in get_level_info
    assert level_id >= -2, "Invalid Level ID provided."
TypeError: '>=' not supported between instances of 'str' and 'int'`

# My code and inputs

`levelToCommentID = input('Level to comment ID> ')`
`commentToLevel = input('Comment> ')`
`level = await client.get_level(levelToCommentID)`
`await level.comment(commentToLevel)`
`print('Done')`

`Level to comment ID> 76834708`
`Comment> amazing`

# My version
- python v3.10.1-final
- gd.py v0.11.0-final
- aiohttp v3.7.4.post0
- click v8.0.3
- system Windows 10 10.0.19044

**Comment by nekitdev** [comment]
Well, you're simply supposed to convert your comment ID to `int` type. For instance:
```python
level_id = int(input(...))
level = await client.get_level(level_id)
```
Let me know if this resolves everything, so I can close this issue.

**Comment by thelittlepony** [comment]
it works! thanks!
